import Header from "../Header/Header";
import Footer from "../Footer/Footer";

import style from "./Layout.module.css";

export default function Layout(props){
    return(
        <>
            <Header></Header>
            <main>
                <div>HOla</div>
                <div>HOla</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
                <div>hola</div>
            </main>

            {props.children}

            <Footer></Footer>
        </>
    );
}